### ISSUE TITLE
Feature Folder Path Not Working on Configuring the Build Step in DevOps

### ISSUE THREAD

**Issue by geraldmaboshe** [SpecFlowOSS/docs.specflow.org#6]
Current Behaviour
The current [docs](https://docs.specflow.org/projects/specflow-livingdoc/en/latest/Generating/Configuring-the-Build-Step-in-DevOps.html) indicate that you specify the path to the Feature folder. With this, tests are displayed as "Other" on DevOps

Expected Behaviour
The docs should indicate the path to be the Root folder

**Comment by alimogithub** [comment]
docs updated
